class DiffHunk
  #
  # @param [Object] Array of hunk object generated by JsDiff.structuredPatch
  # @see https://github.com/kpdecker/jsdiff
  #
  constructor: (@hunk) ->

  getLines: ->
    left  = @hunk.oldStart - 1
    right = @hunk.newStart - 1

    @hunk.lines.map (text) ->
      switch text[0]
        when '-'
          left++
          type = 'deletion'
        when '+'
          right++
          type = 'insertion'
        else
          left++
          right++
          type = 'none'

      createLineObject.call(@, type, text, left, right)

  @boundaryLine: ->
    createLineObject.call(@, 'boundary', '', null, null)

  createLineObject = (type, text, left, right) ->
    {
      type: type
      text: text
      leftLineNumber: left
      rightLineNumber: right
    }

module.exports = DiffHunk
